test_cases = [
    # {"context": "Is this a question?", "question": "What is the question in this text?", "answer": "Is this a question?"},
    # {"context": "This is a statement.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "This is a not statement.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "What time is it?", "question": "What is the question in this text?", "answer": "What time is it?"},
    # {"context": "I'm not sure if this is a question.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "Can you help me?", "question": "What is the question in this text?", "answer": "Can you help me?"},
    # {"context": "The sky is blue.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "How does this work?", "question": "What is the question in this text?", "answer": "How does this work?"},
    # {"context": "It's raining outside.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "Do you know the way to San Jose?", "question": "What is the question in this text?", "answer": "Do you know the way to San Jose?"},
    # {"context": "I like ice cream.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "Why is the sky blue?", "question": "What is the question in this text?", "answer": "Why is the sky blue?"},
    # {"context": "Life is what happens when you're busy making other plans.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "Have you ever seen the rain?", "question": "What is the question in this text?", "answer": "Have you ever seen the rain?"},
    # {"context": "To be or not to be, that is the question.", "question": "What is the question in this text?", "answer": "To be or not to be, that is the question."},
    # {"context": "I wonder if this is a question.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "Could you please pass the salt?", "question": "What is the question in this text?", "answer": "Could you please pass the salt?"},
    # {"context": "The early bird catches the worm.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "Who let the dogs out?", "question": "What is the question in this text?", "answer": "Who let the dogs out?"},
    # {"context": "Actions speak louder than words.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "Isn't it a beautiful day?", "question": "What is the question in this text?", "answer": "Isn't it a beautiful day?"},
    # {"context": "That's a rhetorical question, isn't it?", "question": "What is the question in this text?", "answer": "That's a rhetorical question, isn't it?"},
    # {"context": "She asked if I could come to the party.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "How about we go for a walk?", "question": "What is the question in this text?", "answer": "How about we go for a walk?"},
    # {"context": "I'd like to know more about this topic.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "What if I told you the Earth was flat?", "question": "What is the question in this text?", "answer": "What if I told you the Earth was flat?"},
    # {"context": "It's not rocket science.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "Are we there yet?", "question": "What is the question in this text?", "answer": "Are we there yet?"},
    # {"context": "The question is, will it work?", "question": "What is the question in this text?", "answer": "The question is, will it work?"},
    # {"context": "I'm telling you, not asking.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "You call that a question?", "question": "What is the question in this text?", "answer": ""},
    # {"context": "This statement ends with a question mark?", "question": "What is the question in this text?", "answer": "This statement ends with a question mark?"},
    # {"context": "Just because it ends with a period doesn't mean it's not a question.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "Why bother?", "question": "What is the question in this text?", "answer": "Why bother?"},
    # {"context": "I'm Ron Burgundy?", "question": "What is the question in this text?", "answer": "I'm Ron Burgundy?"},
    # {"context": "Do fish sleep?", "question": "What is the question in this text?", "answer": "Do fish sleep?"},
    # {"context": "The answer, my friend, is blowin' in the wind.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "How much wood would a woodchuck chuck if a woodchuck could chuck wood?", "question": "What is the question in this text?", "answer": "How much wood would a woodchuck chuck if a woodchuck could chuck wood?"},
    # {"context": "I have a dream.", "question": "What is the question in this text?", "answer": ""},
    # {"context": "Et tu, Brute?", "question": "What is the question in this text?", "answer": "Et tu, Brute?"},
    # {"context": "This is not a pipe.", "question": "What is the question in this text?", "answer": ""},
    {"context": "Hi, how are you? I hope everything's okay with you. I heard you were on vacation recently. Where exactly did you go? It must have been great! And what did you enjoy most about the trip?", "question": "What is the question in this text?", "answer": ["Hi, how are you?", "Where exactly did you go?", "And what did you enjoy most about the trip?"]},
    {"context": "The weather has been quite unpredictable lately. One day it's sunny, the next it's raining. Do you think climate change is affecting our local weather patterns?", "question": "What is the question in this text?", "answer": "Do you think climate change is affecting our local weather patterns?"},
    {"context": "I've been thinking about changing careers. It's not an easy decision to make. Have you ever considered a major life change like that?", "question": "What is the question in this text?", "answer": "Have you ever considered a major life change like that?"},
    {"context": "The new restaurant downtown is getting rave reviews. I heard their chef trained in Paris. We should try it sometime, don't you think?", "question": "What is the question in this text?", "answer": "We should try it sometime, don't you think?"},
    {"context": "Life is full of surprises. Sometimes good, sometimes bad. But isn't that what makes it interesting?", "question": "What is the question in this text?", "answer": "But isn't that what makes it interesting?"},
    {"context": "I'm working on a new project at work. It's challenging but rewarding. I'm learning a lot of new skills in the process.", "question": "What is the question in this text?", "answer": ""},
    {"context": "The book you recommended was fantastic. I couldn't put it down. The author's writing style was so engaging.", "question": "What is the question in this text?", "answer": ""},
    {"context": "Can you believe how fast technology is advancing? It seems like there's a new gadget every week. What do you think the next big innovation will be?", "question": "What is the question in this text?", "answer": ["Can you believe how fast technology is advancing?", "What do you think the next big innovation will be?"]},
    {"context": "I've been trying to eat healthier lately. It's not easy with all the temptations around. Do you have any tips for sticking to a healthy diet?", "question": "What is the question in this text?", "answer": "Do you have any tips for sticking to a healthy diet?"},
    {"context": "The concert last night was amazing. The band played all their hits. The crowd was so energetic. I'm still buzzing from the experience.", "question": "What is the question in this text?", "answer": ""},
    {"context": "Have you heard about the new environmental initiative in our city? They're planting trees all over. It's supposed to help reduce carbon emissions. What are your thoughts on this approach?", "question": "What is the question in this text?", "answer": ["Have you heard about the new environmental initiative in our city?", "What are your thoughts on this approach?"]},
    {"context": "I'm planning a surprise party for my best friend. It's been quite stressful keeping it a secret. Do you think she'll like it? I hope everything goes smoothly.", "question": "What is the question in this text?", "answer": "Do you think she'll like it?"},
    {"context": "The history of our town is fascinating. Did you know it was founded over 200 years ago? There are so many interesting stories from the past.", "question": "What is the question in this text?", "answer": "Did you know it was founded over 200 years ago?"},
    {"context": "I've been learning a new language online. It's challenging but fun. They say immersion is the best way to learn. Maybe I should plan a trip to practice?", "question": "What is the question in this text?", "answer": "Maybe I should plan a trip to practice?"},
    {"context": "The new art exhibition at the museum is thought-provoking. It challenges our perceptions of reality. The artist uses unconventional materials to create stunning pieces.", "question": "What is the question in this text?", "answer": ""},
    {"context": "Why do we drive on parkways and park on driveways? Isn't language funny sometimes? These are the kinds of questions that keep me up at night.", "question": "What is the question in this text?", "answer": ["Why do we drive on parkways and park on driveways?", "Isn't language funny sometimes?"]},
    {"context": "I'm considering adopting a pet. It's a big responsibility. Do you have any experience with pets? What kind would you recommend for a first-time owner?", "question": "What is the question in this text?", "answer": ["Do you have any experience with pets?", "What kind would you recommend for a first-time owner?"]},
    {"context": "The documentary about space exploration was mind-blowing. It showed how far we've come in understanding the universe. Yet there's still so much we don't know.", "question": "What is the question in this text?", "answer": ""},
    {"context": "Have you ever wondered why the sky is blue? Or why we dream? These fundamental questions about our world are still being researched by scientists.", "question": "What is the question in this text?", "answer": ["Have you ever wondered why the sky is blue?", "Or why we dream?"]},
    {"context": "The new coffee shop on the corner makes the best lattes. Their pastries are delicious too. We should meet there for our next catch-up.", "question": "What is the question in this text?", "answer": ""}
]