test_cases = [
    ("Is this a question?", ["Is this a question?"]),
    ("This is a statement.", []),
    ("This is a not statement.", []),    
    ("What time is it?", ["What time is it?"]),
    ("I'm not sure if this is a question.", []),
    ("Can you help me?", ["Can you help me?"]),
    ("The sky is blue.", []),
    ("How does this work?", ["How does this work?"]),
    ("It's raining outside.", []),
    ("Do you know the way to San Jose?", ["Do you know the way to San Jose?"]),
    ("I like ice cream.", []),
    ("Why is the sky blue?", ["Why is the sky blue?"]),
    ("Life is what happens when you're busy making other plans.", []),
    ("Have you ever seen the rain?", ["Have you ever seen the rain?"]),
    ("To be or not to be, that is the question.", ["To be or not to be, that is the question."]),
    ("I wonder if this is a question.", []),
    ("Could you please pass the salt?", ["Could you please pass the salt?"]),
    ("The early bird catches the worm.", []),
    ("Who let the dogs out?", ["Who let the dogs out?"]),
    ("Actions speak louder than words.", []),
    ("Isn't it a beautiful day?", ["Isn't it a beautiful day?"]),
    ("That's a rhetorical question, isn't it?", ["That's a rhetorical question, isn't it?"]),
    ("She asked if I could come to the party.", []),
    ("How about we go for a walk?", ["How about we go for a walk?"]),
    ("I'd like to know more about this topic.", []),
    ("What if I told you the Earth was flat?", ["What if I told you the Earth was flat?"]),
    ("It's not rocket science.", []),
    ("Are we there yet?", ["Are we there yet?"]),
    ("The question is, will it work?", ["The question is, will it work?"]),
    ("I'm telling you, not asking.", []),
    ("You call that a question?", []),
    ("This statement ends with a question mark?", ["This statement ends with a question mark?"]),
    ("Just because it ends with a period doesn't mean it's not a question.", []),
    ("Why bother?", ["Why bother?"]),
    ("I'm Ron Burgundy?", ["I'm Ron Burgundy?"]),
    ("Do fish sleep?", ["Do fish sleep?"]),
    ("The answer, my friend, is blowin' in the wind.", []),
    ("How much wood would a woodchuck chuck if a woodchuck could chuck wood?", ["How much wood would a woodchuck chuck if a woodchuck could chuck wood?"]),
    ("I have a dream.", []),
    ("Et tu, Brute?", ["Et tu, Brute?"]),
    ("This is not a pipe.", []),
    ("Hi, how are you? I hope everything's okay with you. I heard you were on vacation recently. Where exactly did you go? It must have been great! And what did you enjoy most about the trip?", ["Hi, how are you?", "Where exactly did you go?", "And what did you enjoy most about the trip?"]),
    ("The weather has been quite unpredictable lately. One day it's sunny, the next it's raining. Do you think climate change is affecting our local weather patterns?", ["Do you think climate change is affecting our local weather patterns?"]),
    ("I've been thinking about changing careers. It's not an easy decision to make. Have you ever considered a major life change like that?", ["Have you ever considered a major life change like that?"]),
    ("The new restaurant downtown is getting rave reviews. I heard their chef trained in Paris. We should try it sometime, don't you think?", ["We should try it sometime, don't you think?"]),
    ("Life is full of surprises. Sometimes good, sometimes bad. But isn't that what makes it interesting?", ["But isn't that what makes it interesting?"]),
    ("I'm working on a new project at work. It's challenging but rewarding. I'm learning a lot of new skills in the process.", []),
    ("The book you recommended was fantastic. I couldn't put it down. The author's writing style was so engaging.", []),
    ("Can you believe how fast technology is advancing? It seems like there's a new gadget every week. What do you think the next big innovation will be?", ["Can you believe how fast technology is advancing?", "What do you think the next big innovation will be?"]),
    ("I've been trying to eat healthier lately. It's not easy with all the temptations around. Do you have any tips for sticking to a healthy diet?", ["Do you have any tips for sticking to a healthy diet?"]),
    ("The concert last night was amazing. The band played all their hits. The crowd was so energetic. I'm still buzzing from the experience.", []),
    ("Have you heard about the new environmental initiative in our city? They're planting trees all over. It's supposed to help reduce carbon emissions. What are your thoughts on this approach?", ["Have you heard about the new environmental initiative in our city?", "What are your thoughts on this approach?"]),
    ("I'm planning a surprise party for my best friend. It's been quite stressful keeping it a secret. Do you think she'll like it? I hope everything goes smoothly.", ["Do you think she'll like it?"]),
    ("The history of our town is fascinating. Did you know it was founded over 200 years ago? There are so many interesting stories from the past.", ["Did you know it was founded over 200 years ago?"]),
    ("I've been learning a new language online. It's challenging but fun. They say immersion is the best way to learn. Maybe I should plan a trip to practice?", ["Maybe I should plan a trip to practice?"]),
    ("The new art exhibition at the museum is thought-provoking. It challenges our perceptions of reality. The artist uses unconventional materials to create stunning pieces.", []),
    ("Why do we drive on parkways and park on driveways? Isn't language funny sometimes? These are the kinds of questions that keep me up at night.", ["Why do we drive on parkways and park on driveways?", "Isn't language funny sometimes?"]),
    ("I'm considering adopting a pet. It's a big responsibility. Do you have any experience with pets? What kind would you recommend for a first-time owner?", ["Do you have any experience with pets?", "What kind would you recommend for a first-time owner?"]),
    ("The documentary about space exploration was mind-blowing. It showed how far we've come in understanding the universe. Yet there's still so much we don't know.", []),
    ("Have you ever wondered why the sky is blue? Or why we dream? These fundamental questions about our world are still being researched by scientists.", ["Have you ever wondered why the sky is blue?", "Or why we dream?"]),
    ("The new coffee shop on the corner makes the best lattes. Their pastries are delicious too. We should meet there for our next catch-up.", ["We should meet there for our next catch-up."]),
    ("Yeah. Of course. And you some I think so. Just to make you a bit louder. Test. Test. Test. Okay. So may maybe I will try to increase the volume. Okay? No. It's fine, actually. It's fine, actually. I think it does a different Yes. So pleasure to see you, and welcome. I'm happy we managed to still do this interview even though some force majeure happened, as I understand. For you. But, like, hopefully, your son's okay. So, my name is Luma. I am from HR at Smart Security, and we have Christopher's with us. He is IT guy from the team for which we look people. So, basically, we both joined today just to tell you more about us, about the position which we have, open. And, of course, we will have questions for you, about you, and, you know, your your vision for your future. So we have 1 hour booked and, and, we will be making notes, so don't mind us typing, please. Just we want to remember facts about you. And, feel free just to ask whenever you have questions because it's not only us choosing, but you as well. You need to figure out if you want to do things we do. So, Martin, I have a little question before we start. Because well, basically, I understand that you applied to this position. So, you probably are looking for the opportunities And my question for you is why? What's happening in your life that you decided to, you know, to look for new opportunities? What's your motivation?", []),
    ("Tell me if it is possible to ask a question without a question mark!", []),
    ("I wonder if it is possible to ask a question without using a question mark.", []),
    ("Tell me what you think about climate change", []),
    ("I wonder how long it takes to learn a new language", []),
    ("Let me know where you'd like to meet", []),
    ("Explain why the sky appears blue", []),
    ("Describe your ideal vacation destination", []),
    ("I'd like to know your opinion on remote work", []),
    ("Share your thoughts on the future of artificial intelligence", []),
    ("Tell me about your favorite childhood memory", []),
    ("I'm curious about your approach to problem-solving", []),
    ("Elaborate on the importance of biodiversity", []),
    ("I was wondering if you could explain the theory of relativity.", []),
    ("Would you mind sharing your thoughts on the current economic situation?", []),
    ("Do you happen to know when the next train arrives?", []),
    ("I'm not sure if you're aware of any good restaurants in the area.", []),
    ("Could you possibly tell me how to get to the nearest post office?", []),
    ("I was hoping you might be able to clarify the company's new policy.", []),
    ("I'm curious as to whether you've ever visited South America.", []),
    ("Have you any idea why the project deadline was extended?", []),
    ("Might I inquire about your experience with coding languages?", []),
    ("I'd be interested to know your perspective on renewable energy sources.",[])
]